name: adn_pay
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.0.0
  flutter_image_slideshow: ^0.1.2
  dio: ^4.0.4
  get: ^4.3.8
  url_launcher: ^6.0.18
  qr_code_scanner: ^0.6.1
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.3.0
  webview_flutter: ^3.0.0
  localstorage: ^4.0.0+1
  get_storage: ^2.0.3
  permission_handler: ^9.1.0
  getwidget: ^2.0.5
  cupertino_icons: ^1.0.2
  pinch_zoom: ^1.0.0
  file_picker: ^4.5.0
  fab_circular_menu: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sample/
